# Generated by Django 5.2.14 on 2026-05-25 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(help_text='Matches external codes like SAP WERKS or Meter IDs', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(help_text='e.g. US, DE, IN', max_length=100)),
                ('grid_subregion', models.CharField(blank=True, help_text='e.g. CAMX, DE-grid', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IataAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=150)),
                ('activity_date', models.DateField(help_text='Specific calendar date this activity took place')),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('emission_factor_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('emission_factor_unit', models.CharField(max_length=50)),
                ('emissions_tco2e', models.DecimalField(decimal_places=6, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPICIOUS', 'Suspicious'), ('FAILED', 'Failed Validation')], default='PENDING_REVIEW', max_length=20)),
                ('anomalies', models.TextField(blank=True, help_text='Detailed error messages or warning flags', null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='True if approved, blocking further edits for audit')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False, help_text='Flagged if values were updated manually after ingestion')),
                ('comments', models.TextField(blank=True, help_text='Analyst commentary or explanation for edits', null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.facility')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.organization')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingestion.organization'),
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=150)),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='Value in metric tonnes of CO2e per unit', max_digits=12)),
                ('factor_unit', models.CharField(help_text='e.g. tCO2e/kWh, tCO2e/liter, tCO2e/passenger-km', max_length=50)),
                ('source', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_emission_factors', to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('INGEST', 'Data Ingestion'), ('EDIT', 'Manual Edit'), ('APPROVE', 'Review & Approval'), ('REJECT', 'Rejection')], max_length=20)),
                ('old_values', models.JSONField(blank=True, help_text='JSON mapping of fields before changes', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='JSON mapping of fields after changes', null=True)),
                ('change_reason', models.TextField(blank=True, help_text='Required explanation for manual adjustments', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='ingestion.normalizedrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RawIngestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP (Fuel/Procurement)'), ('UTILITY', 'Utility Portal Export (Electricity)'), ('TRAVEL', 'Corporate Travel Platform (Concur API)')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.TextField(help_text='Original contents of file or API JSON payload')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='SUCCESS', max_length=20)),
                ('processing_logs', models.TextField(blank=True, null=True)),
                ('ingested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_sources', to='ingestion.organization')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.rawingestionsource'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ANALYST', 'Analyst'), ('ADMIN', 'Administrator'), ('AUDITOR', 'Auditor')], default='ANALYST', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ingestion.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('organization', 'facility_code')},
        ),
    ]
